# Form implementation generated from reading ui file 'animal.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys  # Импортируем модуль sys для работы с системными функциями.
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow  # Импортируем классы для создания основного окна приложения.
from PyQt6.QtGui import QPixmap, QImage  # Импортируем классы для работы с изображениями.
import pygame  # Импортируем библиотеку Pygame для работы со звуком.
import os  # Импортируем модуль os для работы с файловой системой.
from PyQt6.uic import loadUi  # Импортируем функцию loadUi для загрузки интерфейса из .ui файла.


# Определяем класс для основного окна приложения
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Устанавливаем имя объекта для основного окна
        MainWindow.setObjectName("MainWindow")
        # Устанавливаем размеры основного окна
        MainWindow.resize(600, 528)
        # Устанавливаем стиль фона для основного окна
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        # Создаем центральный виджет для основного окна
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        # Создаем кнопку "Кот"
        self.cat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cat.setGeometry(QtCore.QRect(50, 160, 131, 31))  # Устанавливаем положение и размеры кнопки
        self.cat.setStyleSheet("background-color: rgb(255, 255, 255);")  # Устанавливаем стиль кнопки
        self.cat.setObjectName("cat")  # Устанавливаем имя объекта для кнопки
        self.cat.clicked.connect(lambda: self.play_note("cat"))



        # Создаем кнопку "Собака"
        self.dog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dog.setGeometry(QtCore.QRect(230, 160, 131, 31))
        self.dog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dog.setObjectName("dog")
        self.dog.clicked.connect(lambda: self.play_note("dog"))


        # Создаем кнопку "Утка"
        self.duck = QtWidgets.QPushButton(parent=self.centralwidget)
        self.duck.setGeometry(QtCore.QRect(410, 160, 131, 31))
        self.duck.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.duck.setObjectName("duck")
        self.duck.clicked.connect(lambda: self.play_note("duck"))


        # Создаем кнопку "Корова"
        self.cow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cow.setGeometry(QtCore.QRect(230, 390, 131, 31))
        self.cow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cow.setObjectName("cow")
        self.cow.clicked.connect(lambda: self.play_note("cow"))


        # Создаем кнопку "Овца"
        self.sheep = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sheep.setGeometry(QtCore.QRect(50, 390, 131, 31))
        self.sheep.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sheep.setObjectName("sheep")
        self.sheep.clicked.connect(lambda: self.play_note("sheep"))


        # Создаем кнопку "Свинья"
        self.pig = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pig.setGeometry(QtCore.QRect(410, 390, 131, 31))
        self.pig.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pig.setObjectName("pig")
        self.pig.clicked.connect(lambda: self.play_note("pig"))



        # Создаем метку для изображения "Кот"
        self.cat_im = QtWidgets.QLabel(parent=self.centralwidget)
        self.cat_im.setGeometry(QtCore.QRect(50, 40, 131, 111))
        self.cat_im.setText("")  # Удаляем текст
        self.cat_im.setPixmap(
            QtGui.QPixmap("C:/Users/admin/Downloads/animals/animals/кошка.jpg"))  # Устанавливаем изображение
        self.cat_im.setScaledContents(True)  # Масштабируем содержимое метки
        self.cat_im.setObjectName("cat_im")  # Устанавливаем имя объекта для метки


        # Создаем метку для изображения "Собака"
        self.dog_im = QtWidgets.QLabel(parent=self.centralwidget)
        self.dog_im.setGeometry(QtCore.QRect(240, 40, 121, 111))
        self.dog_im.setText("")
        self.dog_im.setPixmap(QtGui.QPixmap("C:/Users/admin/Downloads/animals/animals/собака.jpg"))
        self.dog_im.setScaledContents(True)
        self.dog_im.setObjectName("dog_im")


        # Создаем метку для изображения "Утка"
        self.duck_im = QtWidgets.QLabel(parent=self.centralwidget)
        self.duck_im.setGeometry(QtCore.QRect(410, 40, 121, 111))
        self.duck_im.setText("")
        self.duck_im.setPixmap(QtGui.QPixmap("C:/Users/admin/Downloads/animals/animals/утка.jpg"))
        self.duck_im.setScaledContents(True)
        self.duck_im.setObjectName("duck_im")


        # Создаем метку для изображения "Овца"
        self.sheep_im = QtWidgets.QLabel(parent=self.centralwidget)
        self.sheep_im.setGeometry(QtCore.QRect(60, 260, 121, 111))
        self.sheep_im.setText("")
        self.sheep_im.setPixmap(QtGui.QPixmap("C:/Users/admin/Downloads/animals/animals/овца.jpg"))
        self.sheep_im.setScaledContents(True)
        self.sheep_im.setObjectName("sheep_im")


        # Создаем метку для изображения "Корова"
        self.cow_im = QtWidgets.QLabel(parent=self.centralwidget)
        self.cow_im.setGeometry(QtCore.QRect(240, 260, 111, 111))
        self.cow_im.setText("")
        self.cow_im.setPixmap(QtGui.QPixmap("C:/Users/admin/Downloads/animals/animals/корова.png"))
        self.cow_im.setScaledContents(True)
        self.cow_im.setObjectName("cow_im")


        # Создаем метку для изображения "Свинья"
        self.pig_im = QtWidgets.QLabel(parent=self.centralwidget)
        self.pig_im.setGeometry(QtCore.QRect(410, 270, 121, 101))
        self.pig_im.setText("")
        self.pig_im.setPixmap(QtGui.QPixmap("C:/Users/admin/Downloads/animals/animals/свинья.png"))
        self.pig_im.setScaledContents(True)
        self.pig_im.setObjectName("pig_im")


        pygame.mixer.init()  # Инициализируем модуль микширования Pygame для работы со звуком.


        # Создаем кнопку для воспроизведения звука "Мяу"
        self.myu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.myu.setGeometry(QtCore.QRect(50, 200, 131, 31))
        self.myu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.myu.setObjectName("myu")
        self.myu.clicked.connect(lambda: self.play_note("Мяу"))  # Подключаем обработчик нажатия кнопки


        # Создаем кнопку для воспроизведения звука "Гав"
        self.gav = QtWidgets.QPushButton(parent=self.centralwidget)
        self.gav.setGeometry(QtCore.QRect(230, 200, 131, 31))
        self.gav.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gav.setObjectName("gav")
        self.gav.clicked.connect(lambda: self.play_note("Гав"))


        # Создаем кнопку для воспроизведения звука "Кря"
        self.kry = QtWidgets.QPushButton(parent=self.centralwidget)
        self.kry.setGeometry(QtCore.QRect(410, 200, 131, 31))
        self.kry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.kry.setObjectName("kry")
        self.kry.clicked.connect(lambda: self.play_note("Кря"))


        # Создаем кнопку для воспроизведения звука "Ме"
        self.me = QtWidgets.QPushButton(parent=self.centralwidget)
        self.me.setGeometry(QtCore.QRect(50, 430, 131, 31))
        self.me.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.me.setObjectName("me")
        self.me.clicked.connect(lambda: self.play_note("Ме"))


        # Создаем кнопку для воспроизведения звука "Му"
        self.mu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mu.setGeometry(QtCore.QRect(230, 430, 131, 31))
        self.mu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mu.setObjectName("mu")
        self.mu.clicked.connect(lambda: self.play_note("Му"))


        # Создаем кнопку для воспроизведения звука "Хрю"
        self.hru = QtWidgets.QPushButton(parent=self.centralwidget)
        self.hru.setGeometry(QtCore.QRect(410, 430, 131, 31))
        self.hru.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hru.setObjectName("hru")
        self.hru.clicked.connect(lambda: self.play_note("Хрю"))


        MainWindow.setCentralWidget(self.centralwidget)  # Устанавливаем центральный виджет для основного окна.


        self.retranslateUi(MainWindow)  # Вызываем функцию для перевода текста интерфейса.
        QtCore.QMetaObject.connectSlotsByName(MainWindow)  # Подключаем слоты для сигналов.


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate  # Получаем функцию перевода.
        # Устанавливаем заголовок окна
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


        # Устанавливаем текст для кнопок
        self.cat.setText(_translate("MainWindow", "Кот"))
        self.dog.setText(_translate("MainWindow", "Собака"))
        self.duck.setText(_translate("MainWindow", "Утка"))
        self.cow.setText(_translate("MainWindow", "Корова"))
        self.sheep.setText(_translate("MainWindow", "Овца"))
        self.pig.setText(_translate("MainWindow", "Свинья"))
        self.myu.setText(_translate("MainWindow", "Мяу"))
        self.gav.setText(_translate("MainWindow", "Гав"))
        self.kry.setText(_translate("MainWindow", "Кря"))
        self.me.setText(_translate("MainWindow", "Ме"))
        self.mu.setText(_translate("MainWindow", "Му"))
        self.hru.setText(_translate("MainWindow", "Хрю"))



    def play_note(self, note):
        try:
            # Загружаем звук из файла и воспроизводим его
            sound = pygame.mixer.Sound(f"{note}.mp3")
            sound.play()  # Воспроизводим звук
        except Exception as e:
            print(f"Ошибка при нажатии: {e}")  # Обрабатываем возможные ошибки и выводим сообщение в консоль



# Основной блок, который выполняется при запуске скрипта
if __name__ == "__main__":
    import sys  # Импортируем модуль sys для работы с системными функциями.

    # Создаем экземпляр приложения и окно приложения
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    # Создаем экземпляр класса Ui_MainWindow
    ui = Ui_MainWindow()
    # Настраиваем интерфейс основного окна и показываем основное окно
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())  # Запускаем главный цикл приложения и завершаем его корректно при выходе
